apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: aicore-exe
  annotations:
    scenarios.ai.sap.com/description: "aicore-serve"
    scenarios.ai.sap.com/name: "aicore-serve"
    executables.ai.sap.com/description: "aicore-exe"
    executables.ai.sap.com/name: "aicore-exe"
  labels:
    scenarios.ai.sap.com/id: "aicore-serve"
    ai.sap.com/version: "1.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.l
    spec: |
      predictor:
        imagePullSecrets:
          - name: huggingfacesecret2
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kfserving-container
          image: "321880606331.dkr.ecr.us-east-1.amazonaws.com/huggingface_test:gpt2"
          ports:
            - containerPort: 8080
              protocol: TCP
